### ISSUE TITLE
How to plot a individual transcript for reads densities ?

### ISSUE THREAD

**Issue by junjunlab** [xryanglab/RiboMiner#1]
Hello,thank you for your RiboMiner software! It helped me a lot to analysis my ribo-seq data，but i want to draw a reads density plot on specific transcript ，i do not know how to do it.Thank you for your reply!

**Comment by sherkinglee** [comment]
Hi, thanks for your interest in RiboMiner.  I do have a script to draw a reads density plot on a specific transcript, but it will be added to RiboMiner later on. For now, you can use _RiboDensityAtEachPosition_ function to generate reads density at each position of transcripts and plot it in Excel or R or Python  API.  I hope it will be helpful and if you still have problems, please contact me as soon as possible.

Sherking

**Comment by sherkinglee** [comment]
Hi, for your convenience, I add _CoverageOfEachTrans_ to calculate either read coverage or read density for all transcripts and you can use _PlotTransCoverage_ to visualize the results for your interested transcripts.  Therefore, please update your RiboMiner with _pip install --upgrade RiboMiner_. And please refer to details at **Others** part of [**RiboMiner**](https://github.com/xryanglab/RiboMiner). I hope it will be helpful.

Sherking
