### ISSUE TITLE
KeyError in OutputTranscriptInfo function 

### ISSUE THREAD

**Issue by chenghongdeng** [xryanglab/RiboMiner#13]
Hi, 
When I try to run OutputTranscriptInfo function. I got the error message: 

> Traceback (most recent call last):
>   File "/scratch/cdeng6/myenvs/RiboMiner/bin/OutputTranscriptInfo", line 10, in <mo
> dule>
>     sys.exit(main())
>   File "/scratch/cdeng6/myenvs/RiboMiner/lib/python3.8/site-packages/RiboMiner/Outp
> utTranscriptInfo.py", line 38, in main
>     get_longest_transcripts_information(options.coorFile,options.transcriptFile,opt
> ions.gtfFile,options.longestTransInfo)
>   File "/scratch/cdeng6/myenvs/RiboMiner/lib/python3.8/site-packages/RiboMiner/Func
> tionDefinition.py", line 123, in get_longest_transcripts_information
>     tmp = sorted(list(trans_id),key=lambda x: transLengthDict[x])[-1]
>   File "/scratch/cdeng6/myenvs/RiboMiner/lib/python3.8/site-packages/RiboMiner/Func
> tionDefinition.py", line 123, in <lambda>
>     tmp = sorted(list(trans_id),key=lambda x: transLengthDict[x])[-1]
> KeyError: 'ENST00000641515.2'

I am not sure what cause this problem. Thank you

**Comment by sherkinglee** [comment]
Hi，

I'm not sure how you get this error. Have you checked the _RiboCode_annot/transcripts_cds.txt_ file generated by _prepare_transcripts_? It seems like the transcript ENST00000641515.2 is not presented in the file _RiboCode_annot/transcripts_cds.txt_. Another possible reason is the annotation file you used. The best genome reference and annotation files are from Ensemble genome browser. If you are not using this reference, maybe you can have a try first!

best wishes,
Sherking
