### ISSUE TITLE
OutputTranscriptInfo function error

### ISSUE THREAD

**Issue by junjunlab** [xryanglab/RiboMiner#16]
Hi，I got an error when I run OutputTranscriptInfo function. My gtf and fasta files are from ensembl database. Can you give some advice? Thanks!

![1723959050189](https://github.com/user-attachments/assets/3aae9a45-86bc-473e-bebb-18ae1fd3f906)

**Comment by sherkinglee** [comment]
Hi,
It seems like you did not use the correct transcript_sequences.fa in your command. "-f" is the output file of RiboCode, representing the transcript sequences rather than the genome sequences. You can have a try one more time, and I believe it will work. 

Best wishes

**Comment by junjunlab** [comment]
Thanks, I have solved it.
