### ISSUE TITLE
Transcript length bins on the metagene plot

### ISSUE THREAD

**Issue by aswathyseb** [xryanglab/RiboMiner#18]
Hi,

How can I include the transcript length bin positions/transcript base positions on the x-axis in the metagene plot?

I created the metagene plot using the commands

```
MetageneAnalysisForTheWholeRegions  -f attributes.txt -c longest.transcripts.info.txt -o out/metagene --plot yes

 PlotMetageneAnalysisForTheWholeRegions -i out/metagene_scaled_density_dataframe.txt \
	-o out/metaplot_WT_T1 -g WT,T1 -r WT_1,WT_2,WT_3__T1_1,T1_2,T1_3 --mode mean
```

Any comments are greatly appreciated.

Thank you,

**Comment by sherkinglee** [comment]
Hi,

We did not support the specific position shown in the plot for this function. However, you can use "MetageneAnalysis" function to achieve this. 
For CDS region, please try for example (-u and -d to control the position):
```
MetageneAnalysis -f <attributes.txt> -c <longest.transcripts.info.txt> -o <output_prefix> -U codon -M RPKM -u 0 -d 500 -l 100 -n 10 -m 1 -e 5 --norm yes -y 100 --CI 0.95 --type CDS
```

If you want to contain part of UTRs, please try this (--type to control the regions):
```
MetageneAnalysis -f <attributes.txt> -c <longest.transcripts.info.txt> -o <output_prefix> -U codon -M RPKM -u 100 -d 200 -l 100 -n 10 -m 1 -e 5 --norm yes -y 100 --CI 0.95 --type UTR
```

best wishes

**Comment by aswathyseb** [comment]
Thank you for the prompt reply.  

Two questions,
1) CDS region analysis

I tried the CDS region analysis  using the command

` MetageneAnalysis -f attributes.txt -c ribominer/annot/longest.transcripts.info.txt -o test/out -U codon -M RPKM -u 0 -d 500 -l 100 -n 10 -m 1 -e 5 --norm yes -y 100 --CI 0.95 --type CDS`

Then I tried with the default option for mode, which is the counts as

`MetageneAnalysis -f attributes.txt -c ribominer/annot/longest.transcripts.info.txt -o test/out1 -U codon -u 0 -d 500 --norm yes --type CDS`

**Attached are the plots. The peak at the start codon are different with the two methods. 
Which method is preferred? What is the RPKM filtering criteria?**
[cds_RPKM_filter.pdf](https://github.com/user-attachments/files/17833171/cds_RPKM_filter.pdf)
[cds_count_filter.pdf](https://github.com/user-attachments/files/17833172/cds_count_filter.pdf)

2) I tried to include the UTR region in the command
`MetageneAnalysis -f attributes.txt -c ribominer/annot/longest.transcripts.info.txt -o test/outUTR -U codon -M RPKM -u 100 -d 200 -l 100 -n 10 -m 1 -e 5 --norm yes -y 100 --CI 0.95 --type UTR`

The code ran and I was able to produce the plot, but it gave a runtime warning shown below

`
/Users/asebastian/micromamba/envs/ribominer/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/asebastian/micromamba/envs/ribominer/lib/python3.8/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/asebastian/micromamba/envs/ribominer/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/asebastian/micromamba/envs/ribominer/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/Users/asebastian/micromamba/envs/ribominer/lib/python3.8/site-packages/numpy/core/_methods.py:261: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)`
  
Do you know why am I getting this warning? 
Thanks,

**Comment by aswathyseb** [comment]
Also, to add to my question1 , when I ran the wholeregion analysis I got a smaller peak at the start codon 

[whole_region.pdf](https://github.com/user-attachments/files/17833332/whole_region.pdf)

So, which one is accurate?

**Comment by sherkinglee** [comment]
Hi,

The -M counts or -M RPKM controls the criteria you filter the transcripts and I think there is no differences between them. It is just a way of filtering transcripts. Distinct criteria you choose, distinct transcripts you choose for the analysis and thus different density at the start codon. I think both ways should be OK and you should determine by yourself based on your data. The RPKM means you set RPKM for transcripts filtering. For example, -M RPKM -n 10, means the transcripts with RPKM<10 would not be considered for analysis. The counts for example, -M counts -n 64 , means transcripts with total counts < 64 would be discarded.  As for the warning, maybe it is caused by the update version of numpy. And also, as for the whole region analysis, it is just a way of plotting, all of these are true distribution of your own data. Thus, all should be accurate.

**Comment by aswathyseb** [comment]
Thank you for explaining it in detail. 
It is very helpful. I appreciate it. I will close this issue.
