### ISSUE TITLE
Statistics for the metagene plot

### ISSUE THREAD

**Issue by aswathyseb** [xryanglab/RiboMiner#19]
Hi,

Thank you for Ribominer, it is really easy to work with the tool.

I have produced the metagene plot for the CDs region as shown in the attached.

Is there any statistics I can apply to see if the dip in the ribosome density in my treatment is statistically significant?
Does Ribominer support any?

Thank you for your comments.
[cds_RPKM_filter.pdf](https://github.com/user-attachments/files/17833218/cds_RPKM_filter.pdf)

**Comment by sherkinglee** [comment]
Hi,

We did not provide any statistics for the distribution of the reads. If you want to do that, we recommend calculating the read counts at your interest positions or regions and doing it by yourself. "RiboDensityForSpecificRegion" of RiboMiner could be helpful.

best wishes

**Comment by aswathyseb** [comment]
Thank you! I greatly appreciate it.
