### ISSUE TITLE
Polarity plot 

### ISSUE THREAD

**Issue by aswathyseb** [xryanglab/RiboMiner#20]
Hi,

I noticed that in GitHub it is specified as

`Polarity values is usually used for judging the ribosome density enriched on 5' end of ORFs or 3' end of ORFs. Values colse to -1, indicating ribosomes enriched more on 3' ORFs and values close to 1, indicating ribosomes enriched more on 5' ORFs.` 

Looking at the [main paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03670-8#Sec17), si-eIF5A is enriched more at the 5'end and the polarity plot shows a shift towards -ve score for si-eIF5A.

Is this a typo in the GitHub explanation? 

Shouldn't this be 

Values close to -1 indicate an enrichment on 5'end, and values close to 1 indicate an enrichment on 3'end?

Thank you!

**Comment by sherkinglee** [comment]
Hi,
You are right and thanks for pointing it out, the README has been updated.

best wishes
