### ISSUE TITLE
ribosome densities on each codon

### ISSUE THREAD

**Issue by aswathyseb** [xryanglab/RiboMiner#21]
Hi,

Are the "ribosome densities on each codon" referring to the entire 9-10 codons protected by the ribosome, or specifically the codons in the A and P sites of ribosomes?

Thank you for all your help.

**Comment by sherkinglee** [comment]
Density at codon positions is the P-site density, not all 9-10 codons.

**Comment by aswathyseb** [comment]
Thank you for letting me know.

**Comment by aswathyseb** [comment]
Hi 
I'm sorry to reopen this issue, but is there any way to generate A-site-specific codon densities?

Thanks,

**Comment by sherkinglee** [comment]
Hi,
you can edit the attribute.txt file to get this. The offset length determines what kinds of density you calculate. For example, if you want to get 5'end position density, the offset of each reads should be set as 0 while if you want to get P-site density, the offset should be set as the real off-set length, e.g 12. And if you want to get A-site density, just add 3-nt more to the off-set (if offset=12, the A-site should be 15).

**Comment by aswathyseb** [comment]
Thank you for the explanation,

I am considering only 28bp long reads and the predicted offset is 6. But I get the warning

`The predicted P-site location(6) for length 28 is not the highest peak`

From metaplots [metaplot.pdf](https://github.com/user-attachments/files/17982753/metaplot.pdf), position 0 has the largest peak.  So, I am using 0 as the offset in the attribute file for the metagene analysis. Does that mean 5'end density and p-site densities are the same and I should use 3 in attributes.txt for A-site density? 

How should I approach this?

Thanks again for all your help with this. I greatly appreciate it.

**Comment by aswathyseb** [comment]
I figures it out. The annotation file not having UTRs was the problem of getting wrong offsets.
Thank you for all your help and quick responses.I appreciate it. Closing this issue.
