### ISSUE TITLE
Sample Swapping with PolarityCalculation

### ISSUE THREAD

**Issue by StevenWingett** [xryanglab/RiboMiner#3]
Hi,

Firstly, I wanted to thank you for creating the excellent tool RiboMiner and making it available to the life sciences community.  I am using your tool for my own analysis.

When creating the polarity plots however, I noticed an odd result I thought I should bring to your attention.  I believe RiboMiner may be swapping the samples.

I ran the commands below, using the attached attributes files.  (Essentially, I am processing 6 datasets all together.  I am then processing 2 datasets separately.)

PolarityCalculation -f attributes_github_issue.txt -c longest.transcripts.info.txt -o POLARITY.ALL -n 64

PolarityCalculation -f attributes_con.txt -c longest.transcripts.info.txt -o POLARITY.control -n 64

PolarityCalculation -f attributes_mut.txt -c longest.transcripts.info.txt -o POLARITY.Z -n 64

You can see on the attached graphs that Control1 and Z1 are in different positions on the combined graph as compared to the separate graphs. (It may help you to know that this appears to be related to the names of the bam files.  For example, when the bam files all began with lower case characters this did not happen.)

Please accept my apologies if am making a mistake somewhere, but I need to know that sample swaps are not taking place here or elsewhere before submitting my manuscript.

Please let me know if you have any questions about what I have done to generate these results.

Thank you for your assistance.

Best regards,
Steven

[attributes_con.txt](https://github.com/xryanglab/RiboMiner/files/6703290/attributes_con.txt)
[attributes_github_issue.txt](https://github.com/xryanglab/RiboMiner/files/6703291/attributes_github_issue.txt)
[attributes_mut.txt](https://github.com/xryanglab/RiboMiner/files/6703292/attributes_mut.txt)
[POLARITY.ALL_polarity.pdf](https://github.com/xryanglab/RiboMiner/files/6703293/POLARITY.ALL_polarity.pdf)
[POLARITY.control_polarity.pdf](https://github.com/xryanglab/RiboMiner/files/6703294/POLARITY.control_polarity.pdf)
[POLARITY.Z_polarity.pdf](https://github.com/xryanglab/RiboMiner/files/6703295/POLARITY.Z_polarity.pdf)

**Comment by sherkinglee** [comment]
Hi Steven, 
Thanks for your interests in RiboMiner! I have never met this issue before, so I need time to do some tests and find out what's going on, after which I will tell you soon. But for now, you can do the metagene analyses to check which samples tend to stall more ribosomes at the early translation elongation level (e.g. the first 100 codos).

Best
Sherking

**Comment by sherkinglee** [comment]
Hi Steven,
Thank you for pointing this out! Yes, the direct output plot by _PolarityCalculation_ function indeed exists sample swapping, which was caused by _np.unique(samples)_when the names of bam file are mixed with lower and capital characters.  But the final results of the polarity dataframe with _txt_ format is correct and you can use _PlotPolarity_ to regenerate this plot and you will see the sample orders are correct.
Anyway, I have checked all functions where np.unique() appeared and modified it correctly. I hope there should not be sample swapping again. Thank you again for your reminding!

Best wishes,
Sherking

**Comment by StevenWingett** [comment]
Hi Sherking,

Thanks for getting back to me so quickly and I'm pleased that you were able to resolve the issue.

I was just wondering, should I consider the GitHub master branch as the latest version of RiboMiner or should I always download the "Latest Release" (which is what I am doing at the moment).

Many thanks,

Steven

**Comment by sherkinglee** [comment]
Hi Steven,

It's OK to download the "Latest Release". If you still have any questions about the usage of RiboMiner, please feel free to let me know.

Sherking
