### ISSUE TITLE
Metagene plot error!

### ISSUE THREAD

**Issue by Raoyugithub** [xryanglab/RiboMiner#8]
Hi, I have met the following problem (see the error code) while running the software. Can you help me out? Thanks!
This is the error code:
![image](https://user-images.githubusercontent.com/97614616/149166665-8246b413-f078-4258-9e85-05fe0578af55.png)
This is the attribute.txt: 
![image](https://user-images.githubusercontent.com/97614616/149166723-0294c6e3-248c-4909-968e-596eac5aed1b.png)
This is the longest.transcripts.info.txt
![image](https://user-images.githubusercontent.com/97614616/149166794-8aa6eec8-c882-4c1b-8ef3-f1926187b50f.png)

**Comment by sherkinglee** [comment]
Hi, 
It seems like you installed an older version of RiboMiner. You can update the RiboMiner to version 0.2.3.2 and try it again. But the problem may be the format of your attribute file. Make sure all columns are split by TAB rather than blank space.

Best,
Sherking

**Comment by Raoyugithub** [comment]
Thanks, the attribute file was generated by the script automatically. I will check the attribute file, may also update the software and try again.

**Comment by Raoyugithub** [comment]
> Hi, It seems like you installed an older version of RiboMiner. You can update the RiboMiner to version 0.2.3.2 and try it again. But the problem may be the format of your attribute file. Make sure all columns are split by TAB rather than blank space.
> 
> Best, Sherking

I tiired with the following command:  MetageneAnalysis -i CK/CK_1Aligned.sortedByCoord.out.bam   -c longest.transcripts.info.txt  -o test -s 12,13,13 -t CK1  -r 26,27,28

New errors happen again:

![Uploading image.png…]()

**Comment by Raoyugithub** [comment]
![image](https://user-images.githubusercontent.com/97614616/149295607-8d812ebd-aa34-4e17-8a97-ce1fd2cd3484.png)

**Comment by sherkinglee** [comment]
Oh, I am sorry for making you confused! Actually, the bam file you used for metagene analyses here is the genome bam file. However, MetageneAnalysis requires a bam file with transcriptome level. So you need use the _CK_1Aligned.toTranscriptome.out.sorted.bam_ file for this analysis. By the way, have you succeeded with _MetageneAnalysisForTheWholeRegions_ function as you mentioned for the first time?

Hope you will succeed this time!

best wishes,
Sherking

**Comment by Raoyugithub** [comment]
Hi, Sherking:
With one bam file, it worked.
![image](https://user-images.githubusercontent.com/97614616/149443100-c2167da6-01c4-4007-8b46-6212eb67d5b9.png)
 But with the attribute.txt file, I got a new error:
![image](https://user-images.githubusercontent.com/97614616/149443371-2dedfdf1-5cc3-4977-9049-f7166d25cc61.png)

**Comment by sherkinglee** [comment]
Hi,
I think it is better to present all details about the command and attribute file rather than just your screen plot. For example, the attribute file is like:

```
bamFiles        readLengths     Offsets bamLegends
ctrl1.Aligned.toTranscriptome.out.sorted.bam  28,29,30     12,12,13       Ctrl-1
treat1.Aligned.toTranscriptome.out.sorted.bam      28,29,30     12,12,13       Treat-1
```
And the command you used should be (e.g.):

```
MetageneAnalysisForTheWholeRegions -f attributes.txt -c longest.transcript.info.txt -o test -b 15,90,15 -l 100 -n 10 -m 1 -e 5
```
In your case here, you should use "-f" parameter rather than "-i" with the attribute file.

Sherking

**Comment by Raoyugithub** [comment]
**_Thanks, but I tried the following command line (errors come again):_**
MetageneAnalysisForTheWholeRegions -f  attributes.txt   -c longest.transcripts.info.txt  -o test   -b 15,90,15 -l 100 -n 10 -m 1 -e 5
Traceback (most recent call last):
  File "/public/home/qtxu/anaconda3/bin/MetageneAnalysisForTheWholeRegions", line 11, in <module>
    sys.exit(main())
  File "/public/home/qtxu/anaconda3/lib/python3.7/site-packages/RiboMiner/MetageneAnalysisForTheWholeRegions.py", line 190, in main
    bamFiles,readLengths,Offsets,bamLegends=parse_bamListFile(options.bamListFile)
  File "/public/home/qtxu/anaconda3/lib/python3.7/site-packages/RiboMiner/FunctionDefinition.py", line 394, in parse_bamListFile
    readLengths=line.strip().split("\t")[1]
IndexError: list index out of range

_**This is my attibute file:**_ 

bamFiles	readLengths	Offsets	bamLegends
CK/CK_1_Aligned.toTranscriptome.out_sorted.bam	24,25,26,27,28	8,9,10,11,12	CK-1
CK/CK_2_Aligned.toTranscriptome.out_sorted.bam	24,25,26,27,28	8,9,10,11,12	CK-2
IF/IF_1_Aligned.toTranscriptome.out_sorted.bam	24,25,26,27,28	8,9,10,11,12	IF-1
IF/IF_2_Aligned.toTranscriptome.out_sorted.bam	24,25,26,27,28	8,9,10,11,12	IF-2

**Comment by Raoyugithub** [comment]
Thanks, Now, it works.  Many thanks for your kind help!!!

**Comment by sherkinglee** [comment]
That's great! Enjoy your ribosome profiling data analyses!

**Comment by Raoyugithub** [comment]
**Thanks.** Collectively, it might be  the attribute file problem, I checked and double-checked the file format many times and make sure they are tabbed, but bugs persisted. Finally, I remade the file  from the scratch and issues solved. You are correct, it was the attribute file format issue. **Thanks again,** Besides, mybe the update of the software also helps.
 Hope this will help others.
