### ISSUE TITLE
ribo density on each position or codons?

### ISSUE THREAD

**Issue by junjunlab** [xryanglab/RiboMiner#9]
您好:
   非常感谢您开发了这个非常优秀的Ribo-SEQ的分析软件,我有一些问题没有明白,不知道是否可以请教您?

1. 您是如何计算每个transcript的每个位置的ribo density的,还有如果单位是codon的话,该如何把nt转换为codon?
   
打扰您了,非常期待您的回复!

中国药科大学生科院
张俊

**Comment by sherkinglee** [comment]
Hi, 
The ribosome density is calculated with Pysam package. Specifically, you can easily get all reads mapped to each transcript with Pysam and you can also get the number of reads at each position based on the 5' end of each read aligned to the transcript. If you want to get the codon density, just sum all reads mapped to the 3 nt positions corresponding to that codon. You can refer to the _get_trans_frame_counts()_ function in [RiboMiner](https://github.com/xryanglab/RiboMiner/blob/master/RiboMiner/FunctionDefinition.py).

Best wishes,
Sherking

**Comment by junjunlab** [comment]
Thank you for your reply, I will check it!

Best wishes,
Zhangjun
